config/routes.rb
Rails.application.routes.draw do
  resources :todos
  root to: "todos#index"
  get "follow", to: "dev#follow"
  get "立即預約", to: "dev#order_begin"
  get "平台簡介", to: "dev#follow"
  get "[服務種類] (*type)", to: "dev#service_type"
  get "[服務類型] (*type)", to: "dev#service_select"
  get "[選擇地址] (*location)", to: "dev#service_location"
  get "[設定地址] (*location)", to: "dev#set_location"
  get "[聯絡技師] (*line_id)", to: "dev#contact"
  get "[結束諮詢] (*line_id)", to: "dev#close_contact"
  get "結束諮詢", to: "dev#close_contact"
  get "[接受諮詢] (*line_id)", to: "dev#accept_contact"
  get "[接受訂單] (*line_id)", to: "dev#accept_order"
  get "[技師資訊] (*line_id)", to: "dev#technician_information"
  get "[完成訂單] (*state)", to: "dev#finish_order"
  get "送出訂單", to: "dev#submit_order"
  get "完成訂單", to: "dev#check_finish_order"
  get "test", to: "dev#test"
  get "service_technician", to: "dev#service_technician"
  post "create_comment", to: "dev#create_comment"
  get "new_comment", to: "dev#new_comment"
  post "create_technician", to: "dev#create_technician"
  get "new_technician", to: "dev#new_technician"

  post "create_order", to: "dev#create_order"
  get "new_order/:line_id", to: "dev#new_order"

  post "create_user", to: "dev#create_user"
  get "new_user", to: "dev#new_user"

  get "天氣分析", to: "shooly#weather"
  get "客服電話", to: "shooly#service"
  get "精選文章", to: "shooly#news"
  get "取得天氣", to: "shooly#getweather"

  get "liff_entry", to: "liff#entry"
  post "liff_route", to: "liff#route"
  get "(*other)", to: "dev#other"
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "todos#index"
  # get "個人資料",to: "shooly#profile"
  # get "test",to: "todos#test0"
  # get "我同意Shooly條款", to: "shooly#platform_introduction"
  # get "follow", to: "shooly#platform_introduction"
  # #get "(*date)(*location)天氣", to: "weather#show"
  # #get "(*location)天氣(*other)", to: "weather#show"
  # get "立即預約", to: "shooly#service_type"
  # get "水電維修", to: "shooly#service_plumber"
  # get "居家清潔", to: "shooly#service_home_wash"
  # get "清洗", to: "shooly#service_wash"
  # get "其他", to: "shooly#service_other"
  # get "選擇 (*type)", to: "shooly#service_content"
  # get "地區 (*location1)", to: "shooly#location1"
  # get "縣市 (*location2)", to: "shooly#location2"
  # get "(*location)號", to: "shooly#location"
  # get "(*location)號(*location1)", to: "shooly#location"
  # get "選擇技師 (*technician)", to: "shooly#technician"
  # get "平台簡介", to: "shooly#platform_introduction"
  # get "鄉鎮 (*location3)", to: "shooly#location3"
  # get "確認訂單", to: "shooly#order"
  # get "服務態度(*comment)", to: "shooly#effectiveness"
  # get "效率(*comment)", to: "shooly#technology"
  # get "技術＆專業度(*comment)", to: "shooly#price"
  # get "價錢合理程度(*comment)", to: "shooly#comment"
  # get "付款方式(*pay)", to: "shooly#pay"
  # get "完成訂單", to: "shooly#finish_order"
  # get "技師資訊 (*technician)", to: "shooly#technician_information"
  # get "聯絡技師 (*technician)", to: "shooly#contact"
  # get "結束諮詢", to: "shooly#end_contact"
  # get "取消", to: "shooly#thanks"
  # get "查看技師目前位置", to: "shooly#map"
  # get "map", to: "shooly#map"
  # get "/0", to: "shooly#privacy"
  # get "/1", to: "shooly#order_information"
  # get "/2", to: "shooly#service_home_wash"
  # get "/3", to: "shooly#service_type"
  # get "/4", to: "shooly#service_location"
  # get "/5", to: "shooly#service_other"
  # get "/6", to: "shooly#service_plumber"
  # get "/7", to: "shooly#comment_technician"
  # get "/8", to: "shooly#service_time"
  # get "/9", to: "shooly#service_wash"
  # get "/10", to: "shooly#technician_information"
  # get "/11", to: "shooly#service_technician"
  # get "/12", to: "shooly#pay"
  get "liff_entry", to: "liff#entry"
  post "liff_route", to: "liff#route"
  # get "(*other)", to: "shooly#other"
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :debug_info
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  def test0
    @todos = [
      {
        id: 1,
        name: "ruby",
      },
      {
        id: 2,
        name: "rails",
      },
      {
        id: 3,
        name: "kamiflex",
      },
    ]

    json = Kamiflex.build(self) do
      bubble do
        body do
          horizontal_box do
            text "🍔", flex: 0, action: message_action("/")
            text "Todos"
            text "🆕", align: "end", action: uri_action(new_todo_path)
          end
          separator
          if @todos.present?
            vertical_box margin: "lg" do
              horizontal_box @todos, margin: "lg" do |todo|
                text todo[:name], action: message_action("/todos/#{todo[:id]}")
                text "❌", align: "end", action: message_action("DELETE /todos/#{todo[:id]}")
              end
            end
          else
            text "no contents yet", margin: "lg"
          end
        end
      end
    end

    puts json
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        @todos = Todo.all
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
        format.line { render :index }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
        format.line { render json: flex_text(@todo.errors.to_s) }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        @todos = Todo.all
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
        format.line { render :index }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
        format.line { render json: flex_text(@todo.errors.to_s) }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    @todos = Todo.all
    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
      format.line { render :index }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_params
    params.require(:todo).permit(:name, :desc)
  end

  def debug_info
    puts ""
    puts "=== kamigo debug info start ==="
    puts "platform_type: #{params[:platform_type]}"
    puts "source_type: #{params[:source_type]}"
    puts "source_group_id: #{params[:source_group_id]}"
    puts "source_user_id: #{params[:source_user_id]}"
    puts "=== kamigo debug info end ==="
    puts ""
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/edit.liff.erb
<% content_for :title, "Edit Todo" %>
<%= render "/todos/form.html", todo: @todo %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.desc %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/index.line.erb
<%= raw(Kamiflex.build(self) do
     bubble do
       body do
         horizontal_box do
           text "🍔", flex: 0, action: message_action("/")
           text "Todos", weight: "bold", margin: "sm"
           text "new", align: "end", action: uri_action(liff_path(path: new_todo_path)), color: "#0000ee"
         end
         separator
         if @todos.present?
           vertical_box margin: "lg" do
             horizontal_box margin: "lg" do
               text "Name", weight: "bold"
               text "action", align: "end"
             end
             horizontal_box @todos, margin: "lg" do |todo|
               text todo.name, action: message_action("GET /todos/#{todo.id}")
               text "❌", align: "end", action: message_action("DELETE /todos/#{todo.id}")
             end
           end
         else
           text "沒有目前內容", margin: "lg"
         end
       end
     end
   end) %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/new.liff.erb
<% content_for :title, "New Todo" %>
<%= render "/todos/form.html", todo: @todo %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @todo.desc %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/todos/show.line.erb
<%= raw(Kamiflex.build(self) do
  bubble do
    body do
      horizontal_box do
        text "🍔", flex: 0, action: message_action("/")
        text "Show Todo", weight: "bold", margin: "sm"
        text "edit", align: "end", action: uri_action(liff_path(path: edit_todo_path(@todo) )), color: "#0000ee"
      end
      separator

      horizontal_box margin: "md" do
        vertical_box do
          text "id", weight: "bold", margin: "xs"
          text "name", weight: "bold", margin: "xs"
          text "desc", weight: "bold", margin: "xs"
        end
        vertical_box do
          text @todo.id.blank? ? "-" : @todo.id.to_s, align: "end", margin: "xs"
          text @todo.name.blank? ? "-" : @todo.name.to_s, align: "end", margin: "xs"
          text @todo.desc.blank? ? "-" : @todo.desc.to_s, align: "end", margin: "xs"
        end
      end
    end
  end
end )%>